// <auto-generated />
using System;
using EBANK.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EBANK.Migrations
{
    [DbContext(typeof(OOADContext))]
    partial class OOADContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EBANK.Models.Adresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("Latitude")
                        .HasColumnType("real");

                    b.Property<float>("Longitude")
                        .HasColumnType("real");

                    b.Property<string>("Naziv")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Adresa");
                });

            modelBuilder.Entity("EBANK.Models.Bankomat", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AdresaId")
                        .HasColumnType("int");

                    b.Property<string>("Ime")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("AdresaId");

                    b.ToTable("Bankomat");
                });

            modelBuilder.Entity("EBANK.Models.Filijala", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AdresaId")
                        .HasColumnType("int");

                    b.Property<string>("BrojTelefona")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ime")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AdresaId");

                    b.ToTable("Filijala");
                });

            modelBuilder.Entity("EBANK.Models.Korisnik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KorisnickoIme")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lozinka")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Korisnik");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Korisnik");
                });

            modelBuilder.Entity("EBANK.Models.Kredit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("IsplaceniIznos")
                        .HasColumnType("real");

                    b.Property<DateTime>("PocetakOtpate")
                        .HasColumnType("datetime2");

                    b.Property<int>("StatusKredita")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Kredit");
                });

            modelBuilder.Entity("EBANK.Models.Novost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Naslov")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sadrzaj")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("prikazana")
                        .HasColumnType("bit");

                    b.Property<DateTime>("vrijemeDodavanja")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Novost");
                });

            modelBuilder.Entity("EBANK.Models.Racun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("StanjeRacuna")
                        .HasColumnType("real");

                    b.Property<int>("klijentId")
                        .HasColumnType("int");

                    b.Property<int>("vrstaRacuna")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("klijentId");

                    b.ToTable("Racun");
                });

            modelBuilder.Entity("EBANK.Models.Transakcija", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("Iznos")
                        .HasColumnType("real");

                    b.Property<int>("NacinTransakcije")
                        .HasColumnType("int");

                    b.Property<int>("VrstaTransakcije")
                        .HasColumnType("int");

                    b.Property<int>("naRacunId")
                        .HasColumnType("int");

                    b.Property<int>("saRacunaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("vrijeme")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("naRacunId");

                    b.HasIndex("saRacunaId");

                    b.ToTable("Transakcija");
                });

            modelBuilder.Entity("EBANK.Models.ZahtjevZaKredit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BrojNekretnina")
                        .HasColumnType("int");

                    b.Property<float>("BrojNeplacenihDugova")
                        .HasColumnType("real");

                    b.Property<float>("MjesecniPrihodi")
                        .HasColumnType("real");

                    b.Property<string>("NamjenaKredita")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NazivPoslodavca")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NazivRadnogMjesta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PocetakOtpate")
                        .HasColumnType("datetime2");

                    b.Property<float>("ProsjecniTroskoviDomacinstva")
                        .HasColumnType("real");

                    b.Property<int>("RadniStaz")
                        .HasColumnType("int");

                    b.Property<int>("StatusKredita")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ZahtjevZaKredit");
                });

            modelBuilder.Entity("EBANK.Models.Klijent", b =>
                {
                    b.HasBaseType("EBANK.Models.Korisnik");

                    b.Property<int?>("AdresaId")
                        .HasColumnType("int");

                    b.Property<string>("BrojLicneKarte")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BrojTelefona")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DatumRodjenja")
                        .HasColumnType("datetime2");

                    b.Property<string>("JMBG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Zanimanje")
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("AdresaId");

                    b.HasDiscriminator().HasValue("Klijent");
                });

            modelBuilder.Entity("EBANK.Models.Bankomat", b =>
                {
                    b.HasOne("EBANK.Models.Adresa", "Adresa")
                        .WithMany()
                        .HasForeignKey("AdresaId");
                });

            modelBuilder.Entity("EBANK.Models.Filijala", b =>
                {
                    b.HasOne("EBANK.Models.Adresa", "Adresa")
                        .WithMany()
                        .HasForeignKey("AdresaId");
                });

            modelBuilder.Entity("EBANK.Models.Racun", b =>
                {
                    b.HasOne("EBANK.Models.Klijent", "klijent")
                        .WithMany()
                        .HasForeignKey("klijentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EBANK.Models.Transakcija", b =>
                {
                    b.HasOne("EBANK.Models.Racun", "naRacun")
                        .WithMany()
                        .HasForeignKey("naRacunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EBANK.Models.Racun", "saRacuna")
                        .WithMany()
                        .HasForeignKey("saRacunaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EBANK.Models.Klijent", b =>
                {
                    b.HasOne("EBANK.Models.Adresa", "Adresa")
                        .WithMany()
                        .HasForeignKey("AdresaId");
                });
#pragma warning restore 612, 618
        }
    }
}
